name: nfl_draft
version: '1.0.0'
config-version: 2

profile: 'nfl_draft'

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nfl_draft:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
